version: '3.8'
services:
  dbPostgres:
    image: "postgres:latest"
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: task2023
    volumes:
      - task:/data/postgres/db
    networks:
      - interdb
  pgAdmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@task.com
      PGADMIN_DEFAULT_PASSWORD: task2023
    volumes:
      - task:/data/pgadmin
    networks:
      - interdb
networks:
  default:
    name: task_default
    driver: bridge
  interdb:
    name: task_interdb
    driver: bridge
volumes:
  task: 